// <auto-generated />
namespace SZPD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Academicyear_update3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Academicyear_update3));
        
        string IMigrationMetadata.Id
        {
            get { return "201609061007299_Academicyear_update3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
