// <auto-generated />
namespace SZPD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Thesis_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Thesis_update));
        
        string IMigrationMetadata.Id
        {
            get { return "201609051841519_Thesis_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
